name: Continuous Integration

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minute

jobs:
  build:
   # runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Running Step 1"
      - name: Step 2
        run: echo "Running Step 2"
      - name: Step 3
        run: echo "Running Step 3"
      - name: Step 4
        run: echo "Running Step 4"
      - name: Step 5
        run: echo "Running Step 5"
      - name: Step 6
        run: echo "Running Step 6"
      - name: Step 7
        run: echo "Running Step 7"
      - name: Step 8
        run: echo "Running Step 8"
      - name: Step 9
        run: echo "Running Step 9"
      - name: Step 10
        run: echo "Running Step 10"
      - name: Step 11
        run: echo "Running Step 11"
      - name: Step 12
        run: echo "Running Step 12"
      - name: Step 13
        run: echo "Running Step 13"
      - name: Step 14
        run: echo "Running Step 14"
      - name: Step 15
        run: echo "Running Step 15"
      - name: Step 16
        run: echo "Running Step 16"
      - name: Step 17
        run: echo "Running Step 17"
      - name: Step 18
        run: echo "Running Step 18"
      - name: Step 19
        run: echo "Running Step 19"
      - name: Step 20
        run: echo "Running Step 20"
      - name: Step 21
        run: echo "Running Step 21"
      - name: Step 22
        run: echo "Running Step 22"
      - name: Step 23
        run: echo "Running Step 23"
      - name: Step 24
        run: echo "Running Step 24"
      - name: Step 25
        run: echo "Running Step 25"
